apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: eeki/auth
      context: auth
      docker:
        target: "base"
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eeki/client
      context: client
      docker:
        target: "base"
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
          - src: '**/*.tsx'
            dest: .
    - image: eeki/tickets
      context: tickets
      docker:
        target: "base"
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eeki/orders
      context: orders
      docker:
        target: "base"
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eeki/expiration
      context: expiration
      docker:
        target: "base"
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eeki/payments
      context: payments
      docker:
        target: "base"
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

# Google cloud build
#build:
#  googleCloudBuild:
#    projectId: 'ticketing-dev-324307'
#  artifacts:
#    - image: eu.gcr.io/ticketing-dev-324307/auth
